build site:
  image: node:14.7
  stage: build
  only:
    - dev-aswin
  script:
    - npm install --progress=false
    - npm run build
  artifacts:
    expire_in: 1 week
    paths:
      - dist

unit test:
  image: node:14.7
  stage: test
  only:
    - dev-aswin
  script:
    - npm install --progress=false
    - npm run lint

deploy:
  image: alpine
  stage: deploy
  before_scipt:
    - apk add openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - scp -o StrictHostKeyChecking=no ./dist centos@18.136.58.221:/home/ajdental/public_html
