export default{

    'title': '** Dental Hub **',
    'token': window.localStorage.getItem("token"),
    'users': [],
    'successmessage':'',
    'errormessage':'',
    'message':'',
    'geography': [],
    'activities': [],
    'visualizations':'',
    'visualizations1':'',
    'user_obj':'',
    'adminusername':'',
    'wards_obj':[],
    'address_obj':'',
    'role_obj':[],
    'loginvisualization':'',
    'overview_obj':'',
    'treatment_by_activity_obj':'',
    'treatment_by_ward_obj':'',
    'treatmenttablebasic_obj':'',
    'treatment_table_obj':'',
    'treatmentstrategicdata_obj':'',
    'settingsvisualization':'',
    'sectionaltable_obj':[],
    'treatmentvisualizationbarchart':[],
    'preventionrati_obj':[],
    'earlyintervention_obj':[],
    'recalldistribution_obj':[],
    'wardvisualizationlinechart':[],
    'loginvisualization1':"",
    'activities_obj':[],
}
