export default{

    'title': '** Dental Hub **',
    'token': window.localStorage.getItem("token"),
    'users': [],
    'successmessage':'',
    'errormessage':'',
    'message':'',
    'geography': [],
    'activities': [],
    'visualizations':'',
    'visualizations1':'',
    'user_obj':'',
    'adminusername':'',
    'wards_obj':[],
    'address_obj':'',
    'role_obj':[],
    'loginvisualization':'',
    'table1_obj':'',
    'table2_obj':'',
    'table3_obj':'',
    'table4_obj':'',
    'table5_obj':'',
    'settingsvisualization':'',
    'sectionaltable_obj':[],
    'treatmentvisualizationbarchart':[],
    'treatmentvisualizationlinechart':[],
    'treatmentvisualizationlinechart1':[],
    'treatmentvisualizationlinechart2':[],
    'wardvisualizationlinechart':[],
    'loginvisualization1':"",
    'activities_obj':[],
}
